### ISSUE TITLE
it seems baseline tsv files are not provided

### ISSUE THREAD

**Issue by BrisksHan** [saeyslab/moduledetection-evaluation#6]
I really like your paper and I am trying to use your code to evaluate a community detection algorithms. I got the following error:

baselines = {baseline_name:pd.read_table("../results/modeval_knownmodules/baselines_" + baseline_name + ".tsv", index_col=[0, 1,2]) for baseline_name in baseline_names}

I could not find the file anywhere in the repositories.

Could you please provide the baseline file ?

Best regards,

Han

**Comment by lara-marinelli** [comment]
I encountered the same problem... I really like the paper and I am trying to use the code to evaluate gene expression data and also could not find the baseline tsv files.
Han, were you able to run the code?

**Comment by BrisksHan** [comment]
hi LaraMarinelli,

I could not run the code

**Comment by miltondp** [comment]
I'm having the same issue. Were you guys able to fix them? Could you contact the authors of the paper?

**Comment by rcannood** [comment]
Ping @zouter. Do you have these files still stored somewhere on a backup?

**Comment by miltondp** [comment]
Hi @zouter. Just touching base regarding this issue. Do you think it would be possible to push those files relatively soon (maybe this week) into the repo?

**Comment by zouter** [comment]
Hey everyone
I now have a bunch of deadlines to finish, but will try to look at it next
week.

Sorry for the delay

**Comment by lara-marinelli** [comment]
> I'm having the same issue. Were you guys able to fix them? Could you contact the authors of the paper?

No, I don't. I'm still trying.

**Comment by zouter** [comment]
Sorry everyone, will really try to look at this soon. I have some things to
finish urgently at the moment.

**Comment by zouter** [comment]
Hey everyone, sorry for the delay with this. I've updated the notebooks and data on zenodo, and added results from the top methods in the zenodo folder. Note: there is a new zenodo link
I've also added a more recent E. coli dataset because the old one was from 2016 (the time at which we basically finished the project). Results are still consistent with what we had with the paper.
I've also made several updates to make the code work with more recent python versions (in particular, updates to pandas broke a lot of code). It should run fine now on python 3.7 - 3.9.

Let me know if some things still don't work fine!

**Comment by miltondp** [comment]
Hi @zouter, thank you for this! I'll test it this week.

**Comment by miltondp** [comment]
I downloaded the code, installed the environment as indicated, and I confirm that the code seems to work fine, at least the notebook `1 | Running and evaluating methods.ipynb`. I get the same results, although I didn't run the `dummy` method again as I downloaded the data/results from Zenodo.

One thing that I noticed is that in the cells under "Using the coverage of regulators" several warnings are raised (`RuntimeWarning: divide by zero encountered in log10`). Looks like you didn't run these cells (I don't see any output), so I wonder if that's expected/should be ignored.

![image](https://user-images.githubusercontent.com/172687/135914112-dbf7fc43-ab5a-494f-abf3-3ba359826212.png)

**Comment by miltondp** [comment]
Another difference I see with your outputs (same notebook) is the table generated in section "By comparing with known modules". I guess it's because you probably ran a different detection method and this is not the output of the "dummy" method? Or you didn't fix the initial random seed? You can see below 356 rows, whereas the notebook your pushed has 2581 rows.

![image](https://user-images.githubusercontent.com/172687/135915162-c0923234-2a96-4ca8-957e-c7d3a22ecea5.png)

Same for the output table in section "Using the coverage of regulators", this is the one I got (12 rows), whereas your notebook has 87 rows:

![image](https://user-images.githubusercontent.com/172687/135915542-c16bc7d6-b8fc-4833-b5f2-ef46b4a8c2b9.png)

All the other results below seem to be similar.

If another method was run (different than "dummy") or random seeds were not fixed, it might be good to upload the expected output by either running it with "dummy" or fixing the random seeds, so users are not confused.
